# Generated by Django 3.2.6 on 2023-03-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title here', max_length=30)),
                ('price', models.PositiveIntegerField(help_text='Enter your price here')),
                ('image', models.ImageField(help_text='Upload a photo for this ad', upload_to='images/')),
                ('description', models.CharField(help_text='Write your description here', max_length=400)),
                ('created_at', models.DateField(auto_now_add=True, help_text='The date this ad was created')),
                ('author', models.ForeignKey(help_text='This field stores the author id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter a comment here', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True, help_text='The date this comment was created')),
                ('ad', models.ForeignKey(help_text='This field stores the ad id', on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('author', models.ForeignKey(help_text='This field stores the author id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
