# Generated by Django 3.2.6 on 2023-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this ad was created'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(help_text='Write your description here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Enter a title here', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this comment was created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Enter a comment here', max_length=1000),
        ),
    ]
