# Generated by Django 3.2.6 on 2023-03-13 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20230310_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date this ad was created'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo for this ad', null=True, upload_to='images/'),
        ),
    ]
