# Generated by Django 3.2.6 on 2023-03-10 11:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='This field is used to register and log-in', max_length=30)),
                ('first_name', models.CharField(help_text='First name of user', max_length=30)),
                ('last_name', models.CharField(help_text='Last name of user', max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Your phone number', max_length=20, region='RU')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', help_text='Role of user', max_length=5)),
                ('image', models.ImageField(help_text='Path to an avatar to upload', upload_to='ava/')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
